-- Guaranix: esquema remoto multiusuario para Supabase

create table if not exists public.categorias_gasto (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nombre text not null,
  icono text not null,
  color text not null default '#E0B84B',
  creado_en timestamptz not null default now()
);

create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  categoria_id bigint not null references public.categorias_gasto(id) on delete cascade,
  descripcion text,
  monto numeric not null check (monto >= 0),
  moneda text not null default 'PYG',
  fecha date not null,
  creado_en timestamptz not null default now()
);

create table if not exists public.ingresos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  descripcion text,
  monto numeric not null check (monto >= 0),
  moneda text not null default 'PYG',
  fecha date not null
);

create table if not exists public.presupuesto (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  categoria_id bigint references public.categorias_gasto(id) on delete cascade,
  monto_limite numeric not null check (monto_limite >= 0),
  periodo text not null check (periodo in ('mensual', 'semanal', 'diario')),
  mes_o_semana text not null,
  creado_en timestamptz not null default now()
);

create index if not exists gastos_user_fecha_idx on public.gastos(user_id, fecha desc);
create index if not exists ingresos_user_fecha_idx on public.ingresos(user_id, fecha desc);
create index if not exists presupuesto_user_periodo_idx on public.presupuesto(user_id, periodo, mes_o_semana);

create unique index if not exists presupuesto_general_unico_idx
  on public.presupuesto(user_id, periodo, mes_o_semana)
  where categoria_id is null;

create unique index if not exists presupuesto_categoria_unico_idx
  on public.presupuesto(user_id, categoria_id, periodo, mes_o_semana)
  where categoria_id is not null;

alter table public.categorias_gasto enable row level security;
alter table public.gastos enable row level security;
alter table public.ingresos enable row level security;
alter table public.presupuesto enable row level security;

create policy "usuarios ven sus categorias"
  on public.categorias_gasto for select
  using (auth.uid() = user_id);

create policy "usuarios crean sus categorias"
  on public.categorias_gasto for insert
  with check (auth.uid() = user_id);

create policy "usuarios actualizan sus categorias"
  on public.categorias_gasto for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "usuarios eliminan sus categorias"
  on public.categorias_gasto for delete
  using (auth.uid() = user_id);

create policy "usuarios ven sus gastos"
  on public.gastos for select
  using (auth.uid() = user_id);

create policy "usuarios crean sus gastos"
  on public.gastos for insert
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.categorias_gasto categoria
      where categoria.id = categoria_id and categoria.user_id = auth.uid()
    )
  );

create policy "usuarios actualizan sus gastos"
  on public.gastos for update
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.categorias_gasto categoria
      where categoria.id = categoria_id and categoria.user_id = auth.uid()
    )
  );

create policy "usuarios eliminan sus gastos"
  on public.gastos for delete
  using (auth.uid() = user_id);

create policy "usuarios ven sus ingresos"
  on public.ingresos for select
  using (auth.uid() = user_id);

create policy "usuarios crean sus ingresos"
  on public.ingresos for insert
  with check (auth.uid() = user_id);

create policy "usuarios actualizan sus ingresos"
  on public.ingresos for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "usuarios eliminan sus ingresos"
  on public.ingresos for delete
  using (auth.uid() = user_id);

create policy "usuarios ven sus presupuestos"
  on public.presupuesto for select
  using (auth.uid() = user_id);

create policy "usuarios crean sus presupuestos"
  on public.presupuesto for insert
  with check (
    auth.uid() = user_id
    and (
      categoria_id is null
      or exists (
        select 1 from public.categorias_gasto categoria
        where categoria.id = categoria_id and categoria.user_id = auth.uid()
      )
    )
  );

create policy "usuarios actualizan sus presupuestos"
  on public.presupuesto for update
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and (
      categoria_id is null
      or exists (
        select 1 from public.categorias_gasto categoria
        where categoria.id = categoria_id and categoria.user_id = auth.uid()
      )
    )
  );

create policy "usuarios eliminan sus presupuestos"
  on public.presupuesto for delete
  using (auth.uid() = user_id);

-- Categorias iniciales para cada usuario nuevo.
create or replace function public.crear_categorias_iniciales()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.categorias_gasto (user_id, nombre, icono, color) values
    (new.id, 'Comida', 'silverware-fork-knife', '#E0B84B'),
    (new.id, 'Transporte', 'bus', '#5DA9E9'),
    (new.id, 'Entretenimiento', 'movie-open', '#C084FC'),
    (new.id, 'Servicios', 'flash', '#5CC8A1'),
    (new.id, 'Otro', 'dots-horizontal', '#E57A6D');
  return new;
end;
$$;

drop trigger if exists crear_categorias_despues_registro on auth.users;
create trigger crear_categorias_despues_registro
after insert on auth.users
for each row execute function public.crear_categorias_iniciales();

-- Permite que cada usuario elimine su propia cuenta y todos sus datos asociados.
create or replace function public.eliminar_mi_cuenta()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'No hay un usuario autenticado';
  end if;

  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.eliminar_mi_cuenta() from public;
grant execute on function public.eliminar_mi_cuenta() to authenticated;
